dist: xenial
language: node_js
cache: yarn

before_install:
  - npm install -g yarn@latest

script: true # no tests

before_deploy: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "resistance-sidekick"
  skip_cleanup: true
  local_dir: build
